### ISSUE TITLE
500 on bad input json

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/lib-jersey-multipart-jackson-pojo#9]
When the input body json cannot be parsed into a pojo, the service should throw a 400 instead.

```
2022-10-14 12:28:42.040 [rid:4WJM7] WARN  ErrorMapper:64 - Caught Exception: 
 java.lang.IllegalArgumentException: Could not resolve subtype of [simple type, class org.veupathdb.service.mblast.query.generated.model.BlastQueryConfig]: missing type id property 'tool' (for POJO property 'blastConfig')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.veupathdb.service.mblast.query.generated.model.JobsPostMultipartFormDataImpl["config"]->org.veupathdb.service.mblast.query.generated.model.QueryJobRequestImpl["blastConfig"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324) ~[service.jar:2.0.0]
        at org.veupathdb.lib.jaxrs.raml.multipart.MultipartMessageBodyReader.pojoReadFrom(MultipartMessageBodyReader.kt:252) ~[service.jar:2.0.0]
        at org.veupathdb.lib.jaxrs.raml.multipart.MultipartMessageBodyReader.readFrom(MultipartMessageBodyReader.kt:85) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072) ~[service.jar:2.0.0]
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:888) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:290) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[service.jar:2.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:2.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:2.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:2.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:2.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:2.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[service.jar:2.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[service.jar:2.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) ~[service.jar:2.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:2.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:2.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:2.0.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.veupathdb.service.mblast.query.generated.model.BlastQueryConfig]: missing type id property 'tool' (for POJO property 'blastConfig')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.veupathdb.service.mblast.query.generated.model.JobsPostMultipartFormDataImpl["config"]->org.veupathdb.service.mblast.query.generated.model.QueryJobRequestImpl["blastConfig"])
        at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2083) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1596) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:185) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:119) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1292) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[service.jar:2.0.0]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388) ~[service.jar:2.0.0]
        ... 35 more
```

**Comment by Foxcapades** [comment]
Resolved by v1.0.2
